name: Docker Hub

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub_description.yml

jobs:
  description:
    name: Description
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Docker Hub Description
          uses: peter-evans/dockerhub-description@v2.3.0
          env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKERHUB_REPOSITORY: pedrofracassi/amongcord